version: "3.0"

services:
  api:
    build: ./api
    ports:
      - 3000:8080
    environment:
      - NODE_ENV=production
  ui:
    build: ./ui
    ports:
      - 3005:80
    environment:
      - NODE_ENV=production